4teamwork/ftw.lawgiver

- README.rst
- ftw/lawgiver/actiongroups.py
- ftw/lawgiver/collector.py
- ftw/lawgiver/generator.py
- ftw/lawgiver/interfaces.py
- ftw/lawgiver/meta.py
- ftw/lawgiver/testing.py
- ftw/lawgiver/tests/base.py
- ftw/lawgiver/tests/test_actiongroups.py
- ftw/lawgiver/tests/test_collector.py
- ftw/lawgiver/tests/test_generator_integration.py
- ftw/lawgiver/tests/test_translations.py
There are situations when a permission must be mapped to multiple action groups.
For example when having multiple "add" action groups (for adding different types), the "Add portal content" permission should be in each such action groups.
This can now be achieved by using the optional "move" flag (default: True) of the "map_permissions" directive.
When using move="False", the permission is not removed from the original action group but only added to the new one.
// @mbaechtold @maethu
> Add support for assigning permissions to multiple action groups.

- docs/HISTORY.txt
- ftw/lawgiver/i18nbuilder.py
- ftw/lawgiver/tests/assets/i18nbuilder/profiles/default/workflows/simple_workflow/specification.txt
- ftw/lawgiver/tests/test_i18nbuilder.py
The error happened if the name of the transition in the definition file contained non-ASCII characters.
> Fix UnicodeDecodeError.

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
- ftw/lawgiver/tests/assets/example-4.2/definition.xml
- ftw/lawgiver/tests/assets/example-4.3.4/definition.xml
- ftw/lawgiver/tests/assets/example-4.3.5/definition.xml
- ftw/lawgiver/tests/profiles/role-translation/workflows/role-translation/definition.xml
No longer ignore the permissions `plone.portlet.collection: Add collection portlet` and `plone.portlet.static: Add static portlet` but rather move them to the action group `manage portlets`.
> Map permissions for static portlet and collection portlet.

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
- ftw/lawgiver/tests/assets/example-4.2/definition.xml
- ftw/lawgiver/tests/assets/example-4.3.4/definition.xml
- ftw/lawgiver/tests/assets/example-4.3.5/definition.xml
- ftw/lawgiver/tests/assets/example.definition.xml
- ftw/lawgiver/tests/profiles/custom-workflow/workflows/my_custom_workflow/definition.xml
- ftw/lawgiver/tests/profiles/role-translation/workflows/role-translation/definition.xml
- ftw/lawgiver/tests/profiles/role-translation/workflows/role-translation/result.xml
These permissions cannot be managed because the portal catalog checks the Plone root for these permissions, not the context.
Closes https://github.com/4teamwork/ftw.lawgiver/issues/27.
> Ignore the permissions to access inactive and future content.

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
Since plone.app.contenttypes is standard Plone we add the plone.app.contenttypes mapping to the lawgiver.zcml.
see also https://github.com/4teamwork/ftw.bob.templates/issues/22
closes #66
> Add plone.app.contenttypes permissions to lawgiver.zcml.

- docs/HISTORY.txt
- ftw/lawgiver/browser/speclisting.py
- ftw/lawgiver/browser/templates/speclisting.pt
- ftw/lawgiver/exceptions.py
- ftw/lawgiver/locales/de/LC_MESSAGES/ftw.lawgiver.po
- ftw/lawgiver/locales/ftw.lawgiver.pot
- ftw/lawgiver/testing.py
- ftw/lawgiver/tests/builders.py
- ftw/lawgiver/tests/helpers.py
- ftw/lawgiver/tests/test_updater.py
- ftw/lawgiver/updater.py
In the lawgiver control panel is a button for rebuilding all lawgiver workflows and updating their translations.
This PR adds a new button which does the same but also creates an upgrade step installing the workflow changes.
The upgrade step does only work when there is an `upgrade` package configured as `ftw.upgrade` upgrade step directory.
The upgrade step assumes that all workflows were already installed and updates them.
When the `View` permission was changed, the security indexes are reindexed for the affected objects.
```python
from ftw.upgrade import UpgradeStep
class UpdateWorkflows(UpgradeStep):
"""Update workflows.
"""
def __call__(self):
self.install_upgrade_profile()
self.update_workflow_security(
['workspace-content',
'workspace',
'templates',
'workspaces-folder', …
```
> rebuild specs with upgrade step

- docs/HISTORY.txt
- ftw/lawgiver/locales/de/LC_MESSAGES/ftw.lawgiver.po
I noticed a small typo when using `ftw.lawgiver`, so i quickly reviewed all the german translations and found even more typos 😄 
I think I fixed most of them now.
> Fix typos in german translation files

- README.rst
Correct some common english mistakes and also improve some phrases to be a
bit more readable - hope this is not too opinionated 😉 .
- fix inline literals and use double-backticks everywhere, unlinke markdown RST does not render them as inline literals.
-  drop link to jenkins badge, as it no longer works.
-  unify amount of newlines after a section to two.
> Fix spelling/english/inline literals in readme.

- README.rst
Usually we want to include the main configure.zcml in order to have
the lawgiver.zcml included so that changes can be applied.
Replaced all meta.zcml includes in the readme.
> Update readme: include main lawgiver.zcml.

- docs/HISTORY.txt
- ftw/lawgiver/browser/sharing.py
- ftw/lawgiver/tests/locales/de/LC_MESSAGES/ftw.lawgiver.po
- ftw/lawgiver/tests/locales/de/LC_MESSAGES/plone.po
- ftw/lawgiver/tests/locales/en/LC_MESSAGES/ftw.lawgiver.po
- ftw/lawgiver/tests/locales/en/LC_MESSAGES/plone.po
- ftw/lawgiver/tests/locales/ftw.lawgiver.pot
- ftw/lawgiver/tests/locales/i18n-sync.sh
- ftw/lawgiver/tests/locales/plone.pot
With ``ftw.lawgiver==1.6.1`` the translation of the review state was [changed from translating the state id to translating the state title](https://github.com/4teamwork/ftw.lawgiver/pull/60). This has changed because Plone also uses the review state title.
The role description popup of the sharing page was not updated in that change and thus did not correctly translate the review state title in the table heading.
This change changes the translation behavior of the state in the popup so that we try to translate it the correct way (using the state title) and gracefully fallback to the old behavior by using it as translation default.
```
opengever/core/locales/de/LC_MESSAGES/plone.po:#. Default: "Active"
opengever/core/locales/de/LC_MESSAGES/plone.po-#: …
```
> Fix review state translation in sharing page role description popup.

- docs/HISTORY.txt
- ftw/lawgiver/browser/details.py
- ftw/lawgiver/browser/templates/details.pt
- ftw/lawgiver/locales/de/LC_MESSAGES/ftw.lawgiver.po
- ftw/lawgiver/locales/ftw.lawgiver.pot
- ftw/lawgiver/tests/pages/specdetails.py
- ftw/lawgiver/tests/test_view_details.py
The unmapped permissions in the control panel are now split into two groups: permissions which are explicitly ignored and permissions which unknown: neither ignored nor mapped.
> Control panel: separate unmapped permissions into ignored and unknown groups.

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
This PR ignores the `plone.restapi` permissions
They should be managed through the `rolemap.xml` globally.
> Ignore plone.restapi permissions because they are managed globally.

- README.rst
- docs/HISTORY.txt
- ftw/lawgiver/meta.py
- ftw/lawgiver/meta.zcml
- ftw/lawgiver/tests/test_actiongroups.py
The new lawgiver:workflow directive can be used for grouping statements for one workflow. The workflow attribute can be omitted in the nested ``map_permissions`` and ``ignore`` statements.
Example:
```xml
<configure
xmlns="http://namespaces.zope.org/zope"
xmlns:lawgiver="http://namespaces.zope.org/lawgiver"
i18n_domain="my.package">
<include package="ftw.lawgiver" />
<lawgiver:workflow name="the-workflow">
<lawgiver:map_permissions
action_group="add folder"
permissions="Add folder"
/>
<lawgiver:ignore
permissions="ATContentTypes: View history"
/>
</lawgiver:workflow>
</configure>
```
> Add new lawgiver:workflow directive.

- docs/HISTORY.txt
- ftw/lawgiver/browser/sharing.py
- ftw/lawgiver/tests/locales/de/LC_MESSAGES/plone.po
- ftw/lawgiver/tests/test_sharing_describe_roles.py
When opening the "describing"-overlay in the sharing view for a role with non-ASCII-characters in the title there was an encoding problem when comparing unicode with a bytestring.
> Fix encoding problems in sharing with non-ASCII roles.

- docs/HISTORY.txt
- ftw/lawgiver/browser/configure.zcml
- ftw/lawgiver/meta.zcml
- ftw/lawgiver/testing.py
- ftw/lawgiver/tests/base.py
- ftw/lawgiver/tests/test_actiongroups.py
- ftw/lawgiver/tests/tests.zcml
- ftw/lawgiver/upgrades/configure.zcml
- ftw/lawgiver/wdl/configure.zcml
Some ZCML files and ZCML strings (tests) had incomplete or wrong translation settings.
This eliminates this error in testing:
```
Set up ftw.lawgiver.testing.LawgiverLayer /.../cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py:417: UserWarning: You did not specify an i18n translation domain for the 'action_group' field in <string>
"'%s' field in %s" % (self.getName(), context.info.file )
```
> Fix translation domains in ZCML files.

- README.rst
- docs/HISTORY.txt
- ftw/lawgiver/browser/modifystatus.py
- ftw/lawgiver/tests/test_modifystatus_view.py
The new ModifyStatusViewBase makes it easy to implement custom behavior when executing transitions. It provides the most common functionality for intercepting, enhancing and changing the execution of transitions.
See the readme for further description and example code.
> Base class for custom modify status views.

- setup.py
The tests of ftw.lawgiver are currently not working with ftw.testing=2.0.0.
We are downgrading the dependency here so that the tests work again.
When the problem is fixed in ftw.testing we can upgrade again.
See also: #90
/ cc @buchi
> Downgrade ftw.testing for now.

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
- ftw/lawgiver/tests/assets/example-5.1.0-deletepermission/definition.xml
- ftw/lawgiver/tests/assets/example-5.1.0-no-deletepermission/definition.xml
Although Archetypes and ATContentTypes is still there under Plone 5 it is no logner the standard. plone.app.contenttypes, the Dexterity types, should be used with Plone 5.
In order to clean up our workflows for Plone 5, the default behavior of ftw.lawgiver is changed so that the ATContentTypes permissions are ignored by default under Plone 5.
Users which still use ATContentTypes under Plone 5 may override the action group mapping in their policy package.
At 4teamwork, are not using ATContentTypes under Plone 5 and we are not going to use it in the future.
> Ignore ATContentTypes permissions by default in Plone 5.

- docs/HISTORY.txt
- ftw/lawgiver/tests/base.py
We have switched from unittest2 to unittest recently. Both have a "assertMultiLineEqual", but the latter does handle large datasets very well: unittest.assertMultiLineEqual just displays all on one line when a definition.xml is diffed; what we do.
Therefore the XML diffing is reimplemented so that a unified diff is printed in multiple lines so that the assertion message is readable again for a human being.
> Testing: improve diff output in workflow test for unittest

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
- ftw/lawgiver/localroles.py
- ftw/lawgiver/tests/base.py
- ftw/lawgiver/tests/pages/sharing.py
- ftw/lawgiver/tests/test_sharing.py
- setup.py
- test-plone-4.3.x-deletepermission.cfg
- test-plone-4.3.x-no-deletepermission.cfg
Lawgiver did not work correctly when combined with the REST-API. Indeed in the `DynamicRolesUtility` the context is retrieved from the traversed objects (`request.PARENTS[0]`), which, when the sharing endpoint is called through the REST-API,  is a `RESTWrapper` object and not the object itself. `RESTWrapper` normally delegates everything to `self.context`, but this does not work for certain magic methods, like `__provides__`, which breaks `get_workflow_for` in `DynamicRolesAdapter`. This is fixed here by passing the object itself instead of `RESTWrapper`.
We also needed to pin `zipp` which is an indirect dependency of `plone.restapi` and its latest version is not python 2 compatible.
This is for https://github.com/4teamwork/opengever.core/issues/6041
> Fix bug for sharing view over REST-API.

- docs/HISTORY.txt
- ftw/lawgiver/generator.py
- ftw/lawgiver/i18nbuilder.py
- ftw/lawgiver/tests/assets/example-4.3.5-deletepermission/definition.xml
- ftw/lawgiver/tests/assets/example-4.3.5-no-deletepermission/definition.xml
- ftw/lawgiver/tests/assets/example-5.1.0-deletepermission/definition.xml
- ftw/lawgiver/tests/assets/example-5.1.0-no-deletepermission/definition.xml
- ftw/lawgiver/tests/assets/example.definition.xml
- ftw/lawgiver/tests/locales/en/LC_MESSAGES/plone.po
- ftw/lawgiver/tests/locales/plone.pot
- ftw/lawgiver/tests/profiles/role-translation/workflows/role-translation/definition.xml
- ftw/lawgiver/tests/test_generator_unit.py
- ftw/lawgiver/tests/test_i18nbuilder.py
- ftw/lawgiver/tests/test_view_details.py
Reverts 4teamwork/ftw.lawgiver#97
Until the fix in https://github.com/plone/plone.app.content/pull/192 gets merged we can use the fork https://github.com/4teamwork/plone.app.content/tree/plone_5.1_fixed_non_ascii to fix the UnicodeError. 
This can be done with the following added to the appropriate `cfg` file:
```
auto-checkout =
plone.app.content
[forks]
plone.app.content = 4teamwork
[branches]
plone.app.content = plone_5.1_fixed_non_ascii
```
> Revert "Normalize workflow values."

- docs/HISTORY.txt
- ftw/lawgiver/lawgiver.zcml
The hotfix introduces new permissions which can be ignored.
> Ignore permissions introduced by Products.PloneHotfix20200121.

- test-plone-4.3.x-deletepermission.cfg
- test-plone-4.3.x-no-deletepermission.cfg
- test-plone-5.1.x-deletepermission.cfg
- test-plone-5.1.x-no-deletepermission.cfg
PyJWT >= 2.0.0 has dropped python 2 support, we pin to the latest available compatible version for testing.
See https://pyjwt.readthedocs.io/en/stable/changelog.html#v2-0-0.
pyrsistent >= 0.16.0 has dropped python 2 support, we pin to the latest available compatible version for testing.
See https://github.com/tobgu/pyrsistent/blob/master/CHANGES.txt.
> Pin down PyJWT to 1.7.1 and pyrsistent to 0.16.0 in order to fix tests.

- test-plone-4.3.x-deletepermission.cfg
- test-plone-4.3.x-no-deletepermission.cfg
- test-plone-5.1.x-deletepermission.cfg
- test-plone-5.1.x-no-deletepermission.cfg
The new `plone.restapi` release `8.0.0` drops python 2 and plone 4.3 and 5.1 support.
> Downpin plone.restapi to fix tests.

- test-plone-4.3.x-deletepermission.cfg
- test-plone-4.3.x-no-deletepermission.cfg
The package `jsonschema` has dropped python 2 support in version `4.0.0`.
> Use jsonschema <4.0.0 to fix tests.
